### PR TITLE
Update manifest.json

### PR DESCRIPTION
**Pull request by cmathiswausau**
the en webpage does not work for everyone, I have to use the legacy.for myself.

### CODE REVIEW

**Comment by cmathiswausau** [comment]
thanks for updating this.

I have a question on how you created this, was it just programming or did
you use a specific program to create it?

**Comment by perfilrobo** [comment]
Yes, I always use a text editor with markup for programming. Nothing else.
I write every code line. But the browser API make everything easier.

**Comment by cmathiswausau** [comment]
well I have to tell you that your better at it than I, I cannot look at this stuff for more than 30 min before I start getting a headache. I have been trying to de-cypher the things that dont seem to work for me and help to fix them but again I am no programmer. I dabble a bit and can change lines to better fit my needs.

**Comment by perfilrobo** [comment]
Sometimes I get headache as well. :)
Then I close the laptop, I walk around, drink some water or something. So the brain get easier to process things.

**Pull request merged**
